development:
  adapter: postgresql
  encoding: unicode
  database: dogs_development
  pool: 5
  username: dogs 
  password: dogs
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: dogs_test
  pool: 5
  username: dogs
  password:
  timeout: 5000
